top = '..'

def is_gentoo():
    import subprocess
    try:
        val = subprocess.check_output([
            'uname', '-r'
        ]).decode().strip()
        if 'gentoo' in val:
            return True
    except subprocess.CalledProcessError:
        return ''
    return False

def build(bld):
    matron_sources = [
        'src/config.c',
        'src/device/device.c',
        'src/device/device_hid.c',
        'src/device/device_list.c',
        'src/device/device_midi.c',
        'src/device/device_monitor.c',
        'src/device/device_monome.c',
        'src/device/device_crow.c',
        'src/device/device_serial.c',
        'src/osc.c',
        'src/hardware/battery.c',
        'src/hardware/i2c.c',
        'src/hardware/input.c',
        'src/hardware/io.c',
        'src/hardware/platform.c',
        'src/hardware/screen.c',
        'src/hardware/stat.c',
        # 'src/hardware/screen/ssd1322.c',
        'src/hardware/screen/ssd1322_stub.c',
        'src/hardware/input/gpio.c',
        'src/args.c',
        'src/events.c',
        'src/hello.c',
        'src/input.c',
        'src/jack_client.c',
        'src/lua_eval.c',
        'src/main.c',
        'src/metro.c',
        'src/oracle.c',
        'src/weaver.c',
        'src/screen_events.c',
        'src/screen_results.c',
        'src/snd_file.c',
        'src/system_cmd.c',
        'src/clock.c',
        'src/clocks/clock_internal.c',
        'src/clocks/clock_midi.c',
        'src/clocks/clock_crow.c',
        'src/clocks/clock_scheduler.c',
        'src/time_since.c'
    ]

    if bld.env.NORNS_DESKTOP:
        matron_sources += [
            'src/hardware/screen/sdl.c',
            'src/hardware/input/sdl.c',
        ]

    matron_includes = [
        'src',
        'src/device',
        'src/hardware',
        'lua',
    ]

    matron_libs = [
        'dns_sd', # Why do I have to add this? Waf is dumb.
        'pthread',
        'm',
    ]

    LUANAME = "LUA53"
    if is_gentoo():
        LUANAME = "LUA5.3"

    matron_use = [
        'ALSA',
        'AVAHI-COMPAT-LIBDNS_SD',
        'LIBUDEV',
        'LIBEVDEV',
        'LIBGPIOD',
        'CAIRO',
        'CAIRO-FT',
        LUANAME,
        'LIBLO',
        'LIBMONOME',
        'SNDFILE',
        'JACK',
    ]

    if bld.env.NORNS_DESKTOP:
        matron_libs.append('SDL2')
        matron_use.append('SDL2')

    if bld.env.ENABLE_ABLETON_LINK:
        matron_sources += ['src/clocks/clock_link.c']
        matron_includes += ['../third-party/link/extensions/abl_link/include']
        matron_libs += ['stdc++']
        matron_use += ['LIBLINK_C']

    matron_cflags=['-O3', '-std=c11']

    if bld.env.NORNS_RELEASE:
        matron_cflags += [
            "-Wno-unused-result",
            "-Wno-format-security"
        ]

    if bld.env.PROFILE_MATRON:
      bld.env.append_unique('CFLAGS', ['-pg'])
      bld.env.append_unique('CXXFLAGS', ['-pg'])
      bld.env.append_unique('LDFLAGS', ['-pg'])

    bld.program(features='c cprogram',
        source=matron_sources,
        target='matron',
        includes=matron_includes,
        use=matron_use,
        lib=matron_libs,
        cflags=matron_cflags,
        ldflags=['-Wl,-export-dynamic'])
